services:
  - type: web
    name: tutorspark-week3-study
    runtime: python
    plan: free
    buildCommand: cd TutorSpark && pip install -r requirements.txt
    startCommand: cd TutorSpark && python web_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
